name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build and Test Flutter App
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable

      # Step 3: Install dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Flutter Analyze (Code Quality Check)
      - name: Run Flutter Analyze
        run: flutter analyze

      # Step 5: Run Tests
      - name: Run Tests
        run: flutter test

      # Step 6: Build APK (Optional)
      - name: Build Android APK
        run: flutter build apk --release

    # Step 7: Build iOS (Optional, macOS required)
    # Uncomment the below section if you want to build iOS apps (requires macOS runner).
    # - name: Build iOS
    #   run: flutter build ios --release
    #   env:
    #     CI: true
